// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/el10savio96/artistInsights/src/lib (interfaces: ArtistRepository)
//
// Generated by this command:
//
//	mockgen -destination src/lib/mocks/artist_repository_mock.go -package mocks github.com/el10savio96/artistInsights/src/lib ArtistRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	lib "github.com/el10savio96/artistInsights/src/lib"
	gomock "go.uber.org/mock/gomock"
)

// MockArtistRepository is a mock of ArtistRepository interface.
type MockArtistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArtistRepositoryMockRecorder
	isgomock struct{}
}

// MockArtistRepositoryMockRecorder is the mock recorder for MockArtistRepository.
type MockArtistRepositoryMockRecorder struct {
	mock *MockArtistRepository
}

// NewMockArtistRepository creates a new mock instance.
func NewMockArtistRepository(ctrl *gomock.Controller) *MockArtistRepository {
	mock := &MockArtistRepository{ctrl: ctrl}
	mock.recorder = &MockArtistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtistRepository) EXPECT() *MockArtistRepositoryMockRecorder {
	return m.recorder
}

// GetArtists mocks base method.
func (m *MockArtistRepository) GetArtists(ctx context.Context) ([]lib.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtists", ctx)
	ret0, _ := ret[0].([]lib.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtists indicates an expected call of GetArtists.
func (mr *MockArtistRepositoryMockRecorder) GetArtists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtists", reflect.TypeOf((*MockArtistRepository)(nil).GetArtists), ctx)
}

// GetHeatmap mocks base method.
func (m *MockArtistRepository) GetHeatmap(ctx context.Context, artistID string, start, end time.Time) ([]lib.HeatmapCell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeatmap", ctx, artistID, start, end)
	ret0, _ := ret[0].([]lib.HeatmapCell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeatmap indicates an expected call of GetHeatmap.
func (mr *MockArtistRepositoryMockRecorder) GetHeatmap(ctx, artistID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeatmap", reflect.TypeOf((*MockArtistRepository)(nil).GetHeatmap), ctx, artistID, start, end)
}

// GetHistogram mocks base method.
func (m *MockArtistRepository) GetHistogram(ctx context.Context, artistID string, start, end time.Time, by string) ([]lib.HistogramBin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistogram", ctx, artistID, start, end, by)
	ret0, _ := ret[0].([]lib.HistogramBin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistogram indicates an expected call of GetHistogram.
func (mr *MockArtistRepositoryMockRecorder) GetHistogram(ctx, artistID, start, end, by any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistogram", reflect.TypeOf((*MockArtistRepository)(nil).GetHistogram), ctx, artistID, start, end, by)
}

// GetSeries mocks base method.
func (m *MockArtistRepository) GetSeries(ctx context.Context, artistID string, start, end time.Time, granularity string) ([]lib.SeriesPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeries", ctx, artistID, start, end, granularity)
	ret0, _ := ret[0].([]lib.SeriesPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeries indicates an expected call of GetSeries.
func (mr *MockArtistRepositoryMockRecorder) GetSeries(ctx, artistID, start, end, granularity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeries", reflect.TypeOf((*MockArtistRepository)(nil).GetSeries), ctx, artistID, start, end, granularity)
}

// GetSummary mocks base method.
func (m *MockArtistRepository) GetSummary(ctx context.Context, artistID string, start, end time.Time) (*lib.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, artistID, start, end)
	ret0, _ := ret[0].(*lib.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockArtistRepositoryMockRecorder) GetSummary(ctx, artistID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockArtistRepository)(nil).GetSummary), ctx, artistID, start, end)
}

// GetTopTracks mocks base method.
func (m *MockArtistRepository) GetTopTracks(ctx context.Context, artistID string, start, end time.Time) ([]lib.TrackPlay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopTracks", ctx, artistID, start, end)
	ret0, _ := ret[0].([]lib.TrackPlay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopTracks indicates an expected call of GetTopTracks.
func (mr *MockArtistRepositoryMockRecorder) GetTopTracks(ctx, artistID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopTracks", reflect.TypeOf((*MockArtistRepository)(nil).GetTopTracks), ctx, artistID, start, end)
}

// GetWorldMap mocks base method.
func (m *MockArtistRepository) GetWorldMap(ctx context.Context, artistID string, start, end time.Time) ([]lib.CountryListens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorldMap", ctx, artistID, start, end)
	ret0, _ := ret[0].([]lib.CountryListens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorldMap indicates an expected call of GetWorldMap.
func (mr *MockArtistRepositoryMockRecorder) GetWorldMap(ctx, artistID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorldMap", reflect.TypeOf((*MockArtistRepository)(nil).GetWorldMap), ctx, artistID, start, end)
}
